export const dummyData = [
    {
      deadline: "22-08-222",
      avatar: "./img/author/author-1.jpg",
      preview_image: "./img/items/music-1.jpg",
      price:"1",
      bid:"2",
      max_bid: "1",
      bid_link: "",
      likes: "1",
      name:"test 1",
      username:"test user",
      author_sale:"100"
    },
    {
      deadline: "22-08-222",
      avatar: "./img/author/author-2.jpg",
      preview_image: "./img/items/music-2.jpg",
      price:"1",
      bid:"2",
      max_bid: "1",
      bid_link: "",
      likes: "1",
      name:"test 2",
      username:"test user",
      author_sale:"100"
    },
    {
      deadline: "22-08-222",
      avatar: "./img/author/author-3.jpg",
      preview_image: "./img/items/music-3.jpg",
      price:"1",
      bid:"2",
      max_bid: "1",
      bid_link: "",
      likes: "1",
      name:"test 3",
      username:"test user",
      author_sale:"100"
    },
    {
      deadline: "22-08-222",
      avatar: "./img/author/author-4.jpg",
      preview_image: "./img/items/music-4.jpg",
      price:"1",
      bid:"2",
      max_bid: "1",
      bid_link: "",
      likes: "1",
      name:"test 4",
      username:"test user",
      author_sale:"100"
    },
    {
      deadline: "22-08-222",
      avatar: "./img/author/author-5.jpg",
      preview_image: "./img/items/music-5.jpg",
      price:"1",
      bid:"2",
      max_bid: "1",
      bid_link: "",
      likes: "1",
      name:"test 5",
      username:"test user",
      author_sale:"100"
    },
    {
      deadline: "22-08-222",
      avatar: "./img/author/author-6.jpg",
      preview_image: "./img/items/music-6.jpg",
      price:"1",
      bid:"2",
      max_bid: "1",
      bid_link: "",
      likes: "1",
      name:"test 6",
      username:"test user",
      author_sale:"100"
    },
    {
      deadline: "22-08-222",
      avatar: "./img/author/author-7.jpg",
      preview_image: "./img/items/music-7.jpg",
      price:"1",
      bid:"2",
      max_bid: "1",
      bid_link: "",
      likes: "1",
      name:"test 7",
      username:"test user",
      author_sale:"100"
    },
  ];